# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./frontend/
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Linting - ESLint
      run: npm run ci:eslint
    - name: Linting - Stylelint
      run: npm run ci:stylelint
    - name: Linting - Prettier
      run: npm run ci:prettier
    - name: Test
      run: npm run test